### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by talwagner** [seffyfisher/mavo-locale-he#1]
Hello, thanks for making this! I've noticed a few small issues:
1. "error-uploading" and "cannot-load-uploaded-file" - העלאה במקום טעינה
2. "cant-connect" - האינטרנט - למה ״החופשי״?
--Thanks

**Comment by seffyfisher** [comment]
1.כשמעלים את הקובץ בפועל מבחינת ui זה נראה פחות טוב אבל אני יתקן את זה
2.wishful thinking
3.תודה על הפידבק

**Comment by seffyfisher** [comment]
Hey Tal , just changed the value.
Thanks again for your feedback.
